name: Update Timestamp Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"   # Runs every 5 minutes
  workflow_dispatch:       # Allows manual trigger

jobs:
  update-timestamp:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create or update timestampNew file
        run: |
          mkdir -p data
          echo "Last updated ON: $(TZ='America/Chicago'+date -u '+%Y-%m-%d %H:%M:%S UTC')" > data/timestampNew.txt

      - name: Add and commit timestamp file
        run: |
          git config --global user.name "VamshiKrishna1501"
          git config --global user.email "vamshihoneyy@gmail.com"
          git add data/timestamp.txt
          git diff --cached --quiet || git commit -m "Update timestampNew"
          
      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
